Fix build error
```bash
./pages/_app.tsx:21:8
Type error: 'Component' cannot be used as a JSX component.
  Its element type 'ReactElement<any, any> | Component<{}, any, any> | null' is not a valid JSX element.
    Type 'Component<{}, any, any>' is not assignable to type 'Element | ElementClass | null'.
      Type 'Component<{}, any, any>' is not assignable to type 'ElementClass'.
        The types returned by 'render()' are incompatible between these types.
          Type 'React.ReactNode' is not assignable to type 'import("/Users/9sako6/ghq/github.com/9sako6/9sako6.com/node_modules/@types/react-dom/node_modules/@types/react/index").ReactNode'.
            Type '{}' is not assignable to type 'ReactNode'.
              Type '{}' is missing the following properties from type 'ReactPortal': key, children, type, props

  19 |   return (
  20 |     <ThemeProvider defaultTheme="dark" attribute="class">
> 21 |       <Component {...pageProps} />
     |        ^
  22 |     </ThemeProvider>
  23 |   );
  24 | }

> Build error occurred
Error: Call retries were exceeded
    at ChildProcessWorker.initialize (/Users/9sako6/ghq/github.com/9sako6/9sako6.com/node_modules/next/dist/compiled/jest-worker/index.js:1:11661)
    at ChildProcessWorker._onExit (/Users/9sako6/ghq/github.com/9sako6/9sako6.com/node_modules/next/dist/compiled/jest-worker/index.js:1:12599)
    at ChildProcess.emit (node:events:526:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  type: 'WorkerError'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```