Revert "chore(deps): bump highlight.js from 9.18.1 to 10.4.1"
This reverts commit 70ceaece60a27ab6a9796abc28c49a98db9bc0e6.

Due to:

```
app.b520e6b.js:2 Uncaught TypeError: et.a.registerLanguage is not a function
    at Object.<anonymous> (app.b520e6b.js:2)
    at l (runtime.9cb8add.js:1)
    at Module.<anonymous> (app.b520e6b.js:2)
    at Module.<anonymous> (app.b520e6b.js:2)
    at l (runtime.9cb8add.js:1)
    at Object.<anonymous> (app.b520e6b.js:2)
    at l (runtime.9cb8add.js:1)
    at r (runtime.9cb8add.js:1)
    at Array.t [as push] (runtime.9cb8add.js:1)
    at app.b520e6b.js:2
```